第3回講義 課題提出
fukiueoka/RaiseTech pull request #2
Opened 2024-04-30 08:52 UTC by fukiueoka

## 第3回講義課題
1. サンプルアプリケーションの起動とブラウザでアクセス確認
2. APサーバーに関して
3. DBサーバーに関して
4. 講義で学んだこと, 感想    

#### ご確認よろしくお願いいたします。

2024-04-30 13:23 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-04-30 13:23 UTC, MasatoshiMizumoto commented on lecture03.md
> +2. <u>通信</u>
uタグのスタイリングが効いていない気がしますのでご確認ください！
GitHubで使えるのか私も存じ上げないので、そこから調べたほうが良いかもです！

2024-05-01 00:55 UTC, fukiueoka commented on lecture03.md
> +2. <u>通信</u>
ご確認およびご指摘ありがとうございます！
”<ins></ins>で囲む”にて修正しました。
お手数おかけしますが、再度ご確認よろしくお願いします。

2024-05-01 01:05 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-05-01 01:34 UTC, merged